/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    FilterCheckbox: typeof import('./../components/tablePro/filters/FilterCheckbox.vue')['default']
    FilterDateRange: typeof import('./../components/tablePro/filters/FilterDateRange.vue')['default']
    FilterInput: typeof import('./../components/tablePro/filters/FilterInput.vue')['default']
    FilterNumberRange: typeof import('./../components/tablePro/filters/FilterNumberRange.vue')['default']
    FilterPanel: typeof import('./../components/tablePro/filters/FilterPanel.vue')['default']
    Pagination: typeof import('./../components/tablePro/pagination/Pagination.vue')['default']
    TablePro: typeof import('./../components/tablePro/index.vue')['default']
    TextareaPopoverEdit: typeof import('./../components/tablePro/editors/TextareaPopoverEdit.vue')['default']
  }
}

// For TSX support
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const FilterCheckbox: typeof import('./../components/tablePro/filters/FilterCheckbox.vue')['default']
  const FilterDateRange: typeof import('./../components/tablePro/filters/FilterDateRange.vue')['default']
  const FilterInput: typeof import('./../components/tablePro/filters/FilterInput.vue')['default']
  const FilterNumberRange: typeof import('./../components/tablePro/filters/FilterNumberRange.vue')['default']
  const FilterPanel: typeof import('./../components/tablePro/filters/FilterPanel.vue')['default']
  const Pagination: typeof import('./../components/tablePro/pagination/Pagination.vue')['default']
  const TablePro: typeof import('./../components/tablePro/index.vue')['default']
  const TextareaPopoverEdit: typeof import('./../components/tablePro/editors/TextareaPopoverEdit.vue')['default']
}