/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAvatar: typeof import('./../components/comment/base/BaseAvatar.vue')['default']
    BaseTextarea: typeof import('./../components/comment/base/BaseTextarea.vue')['default']
    Comment: typeof import('./../components/comment/index.vue')['default']
    CommentEditor: typeof import('./../components/comment/components/CommentEditor.vue')['default']
    CommentHeader: typeof import('./../components/comment/components/CommentHeader.vue')['default']
    CommentItem: typeof import('./../components/comment/components/CommentItem.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FilterCheckbox: typeof import('./../components/tablePro/filters/FilterCheckbox.vue')['default']
    FilterDateRange: typeof import('./../components/tablePro/filters/FilterDateRange.vue')['default']
    FilterInput: typeof import('./../components/tablePro/filters/FilterInput.vue')['default']
    FilterNumberRange: typeof import('./../components/tablePro/filters/FilterNumberRange.vue')['default']
    FilterPanel: typeof import('./../components/tablePro/filters/FilterPanel.vue')['default']
    MdEditor: typeof import('./../components/mdEditor/index.vue')['default']
    Pagination: typeof import('./../components/tablePro/pagination/Pagination.vue')['default']
    ReplyItem: typeof import('./../components/comment/components/ReplyItem.vue')['default']
    ReplyList: typeof import('./../components/comment/components/ReplyList.vue')['default']
    TablePro: typeof import('./../components/tablePro/index.vue')['default']
    TextareaPopoverEdit: typeof import('./../components/tablePro/editors/TextareaPopoverEdit.vue')['default']
    VirtualList: typeof import('./../components/comment/components/VirtualList.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const BaseAvatar: typeof import('./../components/comment/base/BaseAvatar.vue')['default']
  const BaseTextarea: typeof import('./../components/comment/base/BaseTextarea.vue')['default']
  const Comment: typeof import('./../components/comment/index.vue')['default']
  const CommentEditor: typeof import('./../components/comment/components/CommentEditor.vue')['default']
  const CommentHeader: typeof import('./../components/comment/components/CommentHeader.vue')['default']
  const CommentItem: typeof import('./../components/comment/components/CommentItem.vue')['default']
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElCollapse: typeof import('element-plus/es')['ElCollapse']
  const ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const FilterCheckbox: typeof import('./../components/tablePro/filters/FilterCheckbox.vue')['default']
  const FilterDateRange: typeof import('./../components/tablePro/filters/FilterDateRange.vue')['default']
  const FilterInput: typeof import('./../components/tablePro/filters/FilterInput.vue')['default']
  const FilterNumberRange: typeof import('./../components/tablePro/filters/FilterNumberRange.vue')['default']
  const FilterPanel: typeof import('./../components/tablePro/filters/FilterPanel.vue')['default']
  const MdEditor: typeof import('./../components/mdEditor/index.vue')['default']
  const Pagination: typeof import('./../components/tablePro/pagination/Pagination.vue')['default']
  const ReplyItem: typeof import('./../components/comment/components/ReplyItem.vue')['default']
  const ReplyList: typeof import('./../components/comment/components/ReplyList.vue')['default']
  const TablePro: typeof import('./../components/tablePro/index.vue')['default']
  const TextareaPopoverEdit: typeof import('./../components/tablePro/editors/TextareaPopoverEdit.vue')['default']
  const VirtualList: typeof import('./../components/comment/components/VirtualList.vue')['default']
}